name: CD Production Pipeline
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Kubernetes
        uses: Azure/setup-kubectl@v3
        
      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
        
      - name: Start Minikube
        run: |
          minikube start
          minikube addons enable ingress
        
      - name: Create namespace
        run: |
          kubectl create namespace weather-app --dry-run=client -o yaml | kubectl apply -f -
        
      - name: Create secrets
        run: |
          echo "${{ secrets.WEATHER_API_KEY }}" | base64 > weather-api-key.txt
          kubectl create secret generic weather-secrets \
            --from-file=api-key=weather-api-key.txt \
            -n weather-app \
            --dry-run=client -o yaml | kubectl apply -f -
          rm weather-api-key.txt
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -k k8s/
          kubectl get all -n weather-app
          
      - name: Wait for deployments
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/backend-deployment -n weather-app
          kubectl wait --for=condition=available --timeout=300s deployment/frontend-deployment -n weather-app
          
      - name: Get service URLs
        run: |
          minikube service list -n weather-app