name: CD Production Pipeline
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Kubernetes
        uses: Azure/setup-kubectl@v3
        
      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
        
      - name: Configure Minikube
        run: |
          minikube start
          minikube addons enable ingress
          # Wait for ingress controller
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s
        
      - name: Create namespace
        run: |
          kubectl create namespace weather-app --dry-run=client -o yaml | kubectl apply -f -
        
      - name: Create secrets
        run: |
          echo "${{ secrets.WEATHER_API_KEY }}" | base64 > weather-api-key.txt
          kubectl create secret generic weather-secrets \
            --from-file=api-key=weather-api-key.txt \
            -n weather-app \
            --dry-run=client -o yaml | kubectl apply -f -
          rm weather-api-key.txt
        
      - name: Deploy core resources
        run: |
          # Apply everything except ingress first
          kubectl apply -f k8s/configmap.yaml -n weather-app
          kubectl apply -f k8s/service.yaml -n weather-app
          kubectl apply -f k8s/deployment.yaml -n weather-app
          kubectl apply -f k8s/persistent-volume.yaml -n weather-app
        
      - name: Deploy ingress
        run: |
          # Apply ingress after other resources are ready
          kubectl apply -f k8s/ingress.yaml -n weather-app
          
      - name: Wait for deployments
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/backend-deployment -n weather-app
          kubectl wait --for=condition=available --timeout=300s deployment/frontend-deployment -n weather-app
          
      - name: Get service URLs
        run: |
          minikube service list -n weather-app